Add Jjjjfiles

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -2,61 +2,50 @@ pipeline {
     agent any
 
     environment {
-        FLASK_APP = 'app.py'
-        VENV_PATH = 'venv'
-        DEPLOY_DIR = 'service_app'
+        DOCKER_IMAGE = 'opamao/newsapi101'
+        DOCKER_TAG = 'latest'
     }
 
     stages {
         stage('Clone from GitHub') {
             steps {
-                checkout([$class: 'GitSCM',
-                    branches: [[name: 'main']],  // Specify 'main' branch
-                    userRemoteConfigs: [[url: 'https://github.com/opamao1/NewsApi.git']]])
+                checkout([
+                    $class: 'GitSCM',
+                    branches: [[name: 'main']],
+                    userRemoteConfigs: [[url: 'https://github.com/opamao1/NewsApi.git']]
+                ])
             }
         }
 
-        stage('Build python environment') {
-            // in this state, we will install create venv, install the dependencies
-
+        stage('Build Docker image') {
             steps {
-                sh 'cd /'
-                sh "python3 -m venv ${VENV_PATH}"
-                sh 'pwd && ls'
-                sh " . ${VENV_PATH}/bin/activate"
-            //sh 'pip3 install -r requirements.txt'
+                script {
+                    sh "docker build -t ${env.DOCKER_IMAGE}:${env.DOCKER_TAG} ."
+                }
             }
         }
 
-        stage('Run test') {
+        stage('Run Docker container') {
             steps {
-                sh 'echo connected to Sonarqube'
-                sh 'echo application tests successful'
+                script {
+                    sh "docker run -d -p 5000:5000 --name newscontainer ${env.DOCKER_IMAGE}:${env.DOCKER_TAG}"
+                }
             }
         }
+    }
 
-        stage('deploy state') {
-            // This stage will deploy to the python application to the correct dir
-
-            steps {
-
-                sh """
-                pwd && ls
-                . ${VENV_PATH}/bin/activate
-                cd .venv
-                pip3 install -r requirements.txt
-                mkdir -p ${DEPLOY_DIR}
-                ls
-                cp  app.py ${DEPLOY_DIR}
-                cp  -r Data ${DEPLOY_DIR}
-                cp  -r services ${DEPLOY_DIR}
-                cp  -r templates ${DEPLOY_DIR}
-                cd ${DEPLOY_DIR}
-                ls
-                flask run --port=5001
-
-                 """
+    post {
+        always {
+            script {
+                sh 'docker rm -f newscontainer || true'
+                sh 'docker rmi ${env.DOCKER_IMAGE}:${env.DOCKER_TAG} || true'
             }
+        }
+        success {
+            echo 'The build and deploymentt were successful!'
+        }
+        failure {
+            echo 'The build or deployment failed.'
         }
     }
 }
